#define WIN32_LEAN_AND_MEAN
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
#pragma comment(lib, "ws2_32.lib")
#define MAX_SNI_LIST 16
#define MAX_TTL_LIST 8
#define MAX_SERVER_LIST 32
#define MAX_FALLBACK_PORTS 8
typedef struct { char host[64]; int port; int family; } ServerAddr;
typedef struct {
    int listen_port;
    ServerAddr servers[32];
    int server_count;
    int fallback_ports[8];
    int fallback_port_count;
    char sni_list[16][256];
    int sni_count;
    int ttl_list[8];
    int ttl_count;
    int jitter_min_ms;
    int jitter_max_ms;
    int fragment_real;
    int adaptive;
    int randomize_sni_case;
    char log_file_path[256];
} Config;
static Config g_cfg = {40443,{{0}},0,{0},0,{{0}},0,{0},0,20,80,0,1,0,""};
static char *trim(char *s){while(isspace((unsigned char)*s))s++;if(!*s)return s;char*e=s+strlen(s)-1;while(e>s&&isspace((unsigned char)*e))*e--='\0';return s;}
static int is_raw_ip(const char*s,int*f){struct in_addr a4;struct in6_addr a6;if(InetPtonA(AF_INET,s,&a4)==1){*f=AF_INET;return 1;}if(InetPtonA(AF_INET6,s,&a6)==1){*f=AF_INET6;return 1;}return 0;}
static void parse_sni_list(const char*v){char buf[2048];strncpy(buf,v,sizeof(buf)-1);buf[sizeof(buf)-1]=0;g_cfg.sni_count=0;char*ctx=NULL;char*tok=strtok_s(buf,",",&ctx);while(tok&&g_cfg.sni_count<16){strncpy(g_cfg.sni_list[g_cfg.sni_count],trim(tok),255);g_cfg.sni_count++;tok=strtok_s(NULL,",",&ctx);}}
static void parse_ttl_list(const char*v){char buf[256];strncpy(buf,v,sizeof(buf)-1);buf[sizeof(buf)-1]=0;g_cfg.ttl_count=0;char*ctx=NULL;char*tok=strtok_s(buf,",",&ctx);while(tok&&g_cfg.ttl_count<8){char*t=trim(tok);char*e=NULL;long val=strtol(t,&e,10);if(e!=t)g_cfg.ttl_list[g_cfg.ttl_count++]=(int)val;tok=strtok_s(NULL,",",&ctx);}}
static void parse_fallback_ports(const char*v){char buf[256];strncpy(buf,v,sizeof(buf)-1);buf[sizeof(buf)-1]=0;g_cfg.fallback_port_count=0;char*ctx=NULL;char*tok=strtok_s(buf,",",&ctx);while(tok&&g_cfg.fallback_port_count<8){char*t=trim(tok);char*e=NULL;long val=strtol(t,&e,10);if(e!=t)g_cfg.fallback_ports[g_cfg.fallback_port_count++]=(int)val;tok=strtok_s(NULL,",",&ctx);}}
static ServerAddr g_raw_servers[32]; static int g_raw_count=0;
static void parse_one_server(char*e){if(g_raw_count>=32)return;char*host=e;char h[64];int port=0;if(e[0]=='['){char*c=strchr(e,']');if(!c)return;size_t hl=c-e-1;if(hl>=64)hl=63;strncpy(h,e+1,hl);h[hl]=0;char*col=strchr(c,':');if(col){char*en=NULL;long v=strtol(col+1,&en,10);if(en!=col+1)port=(int)v;}int f;if(!is_raw_ip(h,&f))return;strncpy(g_raw_servers[g_raw_count].host,h,63);g_raw_servers[g_raw_count].family=f;g_raw_servers[g_raw_count].port=port;g_raw_count++;}else{const char*col=strrchr(e,':');if(!col){strncpy(h,e,63);h[63]=0;}else{size_t hl=col-e;if(hl>=64)hl=63;strncpy(h,e,hl);h[hl]=0;char*en=NULL;long v=strtol(col+1,&en,10);if(en!=col+1)port=(int)v;}int f;if(!is_raw_ip(h,&f))return;strncpy(g_raw_servers[g_raw_count].host,h,63);g_raw_servers[g_raw_count].family=f;g_raw_servers[g_raw_count].port=port;g_raw_count++;}}
static void parse_connect_list(const char*v){char buf[1024];strncpy(buf,v,sizeof(buf)-1);buf[sizeof(buf)-1]=0;g_raw_count=0;char*ctx=NULL;char*tok=strtok_s(buf,",",&ctx);while(tok){parse_one_server(trim(tok));tok=strtok_s(NULL,",",&ctx);}}
static void expand_servers(void){g_cfg.server_count=0;for(int i=0;i<g_raw_count;i++){if(g_raw_servers[i].port!=0){if(g_cfg.server_count>=32)break;g_cfg.servers[g_cfg.server_count].family=g_raw_servers[i].family;strncpy(g_cfg.servers[g_cfg.server_count].host,g_raw_servers[i].host,63);g_cfg.servers[g_cfg.server_count].port=g_raw_servers[i].port;g_cfg.server_count++;}else{for(int j=0;j<g_cfg.fallback_port_count;j++){if(g_cfg.server_count>=32)break;g_cfg.servers[g_cfg.server_count].family=g_raw_servers[i].family;strncpy(g_cfg.servers[g_cfg.server_count].host,g_raw_servers[i].host,63);g_cfg.servers[g_cfg.server_count].port=g_cfg.fallback_ports[j];g_cfg.server_count++;}}}}
static int as_bool(const char*v){return !_stricmp(v,"true")||!_stricmp(v,"yes")||!_stricmp(v,"1")||!_stricmp(v,"on");}
static void apply_setting(const char*k,const char*v){if(!_stricmp(k,"listen_port")){char*e=NULL;long val=strtol(v,&e,10);if(e!=v)g_cfg.listen_port=(int)val;}else if(!_stricmp(k,"connect_list"))parse_connect_list(v);else if(!_stricmp(k,"fallback_ports"))parse_fallback_ports(v);else if(!_stricmp(k,"sni_list"))parse_sni_list(v);else if(!_stricmp(k,"ttl_list"))parse_ttl_list(v);else if(!_stricmp(k,"jitter_min_ms")){char*e=NULL;long val=strtol(v,&e,10);if(e!=v)g_cfg.jitter_min_ms=(int)val;}else if(!_stricmp(k,"jitter_max_ms")){char*e=NULL;long val=strtol(v,&e,10);if(e!=v)g_cfg.jitter_max_ms=(int)val;}else if(!_stricmp(k,"fragment"))g_cfg.fragment_real=as_bool(v);else if(!_stricmp(k,"adaptive"))g_cfg.adaptive=as_bool(v);else if(!_stricmp(k,"randomize_sni_case"))g_cfg.randomize_sni_case=as_bool(v);else if(!_stricmp(k,"log_file"))strncpy(g_cfg.log_file_path,v,255);}
static int load_config(const char*p){FILE*f=fopen(p,"r");if(!f)return -1;char line[2048];while(fgets(line,sizeof(line),f)){char*s=trim(line);if(!*s||*s=='#')continue;char*e=strchr(s,'=');if(!e)continue;*e=0;apply_setting(trim(s),trim(e+1));}fclose(f);return 0;}
static void put_u16(unsigned char*b,size_t *pp,unsigned short v){b[(*pp)++]=(v>>8)&0xFF;b[(*pp)++]=v&0xFF;}
static size_t build_fake_client_hello(unsigned char*out,size_t cap,const char*sni){size_t sl=strlen(sni);unsigned char body[1024];size_t p=0;body[p++]=0x03;body[p++]=0x03;for(int i=0;i<32;i++)body[p++]=(unsigned char)(rand()&0xFF);body[p++]=0x00;static unsigned short dc[]={0x1301,0x1302,0x1303,0xC02B,0xC02F,0xC02C,0xC030,0xCCA9,0xCCA8,0xC013,0xC014,0x009C,0x009D,0x002F,0x0035};put_u16(body,&p,(unsigned short)(14*2));for(int i=0;i<14;i++)put_u16(body,&p,dc[i]);body[p++]=0x01;body[p++]=0x00;size_t ep=p;p+=2;size_t es=p;put_u16(body,&p,0x0000);put_u16(body,&p,(unsigned short)(sl+5));put_u16(body,&p,(unsigned short)(sl+3));body[p++]=0x00;put_u16(body,&p,(unsigned short)sl);memcpy(body+p,sni,sl);p+=sl;put_u16(body,&p,0x0017);put_u16(body,&p,0x0000);put_u16(body,&p,0xFF01);put_u16(body,&p,0x0001);body[p++]=0x00;put_u16(body,&p,0x000A);put_u16(body,&p,0x0008);put_u16(body,&p,0x0006);put_u16(body,&p,0x001D);put_u16(body,&p,0x0017);put_u16(body,&p,0x0018);put_u16(body,&p,0x000B);put_u16(body,&p,0x0002);body[p++]=0x01;body[p++]=0x00;put_u16(body,&p,0x0023);put_u16(body,&p,0x0000);put_u16(body,&p,0x0010);put_u16(body,&p,0x000E);put_u16(body,&p,0x000C);body[p++]=0x02;body[p++]=0x68;body[p++]=0x32;body[p++]=0x08;memcpy(body+p,"http/1.1",8);p+=8;put_u16(body,&p,0x0005);put_u16(body,&p,0x0005);body[p++]=0x01;put_u16(body,&p,0x0000);put_u16(body,&p,0x0000);put_u16(body,&p,0x000D);put_u16(body,&p,0x0020);put_u16(body,&p,0x0020);static unsigned short sigs[]={0x0403,0x0503,0x0603,0x0807,0x0808,0x0809,0x080A,0x080B,0x0804,0x0805,0x0806,0x0401,0x0501,0x0601,0x0203,0x0201};for(int i=0;i<16;i++)put_u16(body,&p,sigs[i]);put_u16(body,&p,0x0033);put_u16(body,&p,0x0026);put_u16(body,&p,0x0024);put_u16(body,&p,0x001D);put_u16(body,&p,0x0020);for(int i=0;i<32;i++)body[p++]=(unsigned char)(rand()&0xFF);put_u16(body,&p,0x002D);put_u16(body,&p,0x0002);body[p++]=0x01;body[p++]=0x01;put_u16(body,&p,0x002B);put_u16(body,&p,0x0005);body[p++]=0x04;put_u16(body,&p,0x0304);put_u16(body,&p,0x0303);size_t et=p-es;body[ep]=(et>>8)&0xFF;body[ep+1]=et&0xFF;size_t bl=p;unsigned char hs[1100];hs[0]=0x01;hs[1]=(bl>>16)&0xFF;hs[2]=(bl>>8)&0xFF;hs[3]=bl&0xFF;memcpy(hs+4,body,bl);size_t hl=4+bl;if(cap<hl+5)return 0;out[0]=0x16;out[1]=0x03;out[2]=0x01;out[3]=(hl>>8)&0xFF;out[4]=hl&0xFF;memcpy(out+5,hs,hl);return hl+5;}
static int send_all(SOCKET fd,const void*buf,size_t len){const unsigned char*p=buf;size_t s=0;while(s<len){int n=send(fd,(const char*)p+s,(int)(len-s),0);if(n==SOCKET_ERROR){if(WSAGetLastError()==WSAEINTR)continue;return -1;}if(n==0)break;s+=n;}return (int)s;}
static const char* pick_random_sni(void){if(g_cfg.sni_count==0)return "www.hcaptcha.com";return g_cfg.sni_list[rand()%g_cfg.sni_count];}
static void randomize_sni_case(const char*s,char*o,size_t cap){size_t len=strlen(s);if(len+1>cap)len=cap-1;for(size_t i=0;i<len;i++){char c=s[i];if(isalpha((unsigned char)c)&&(rand()%2))c=isupper((unsigned char)c)?(char)tolower((unsigned char)c):(char)toupper((unsigned char)c);o[i]=c;}o[len]=0;}
static void set_ttl(SOCKET fd,int fam,int ttl){if(fam==AF_INET)setsockopt(fd,IPPROTO_IP,IP_TTL,(char*)&ttl,sizeof(ttl));else setsockopt(fd,IPPROTO_IPV6,IPV6_UNICAST_HOPS,(char*)&ttl,sizeof(ttl));}
static void send_one_decoy(ServerAddr*srv,int ttl){const char*sni=pick_random_sni();char cs[256];if(g_cfg.randomize_sni_case){randomize_sni_case(sni,cs,sizeof(cs));sni=cs;}SOCKET fd=socket(srv->family,SOCK_STREAM,IPPROTO_TCP);if(fd==INVALID_SOCKET)return;set_ttl(fd,srv->family,ttl);struct sockaddr_storage dst;int dlen=0;memset(&dst,0,sizeof(dst));if(srv->family==AF_INET){struct sockaddr_in*a=(struct sockaddr_in*)&dst;a->sin_family=AF_INET;a->sin_port=htons(srv->port);InetPtonA(AF_INET,srv->host,&a->sin_addr);dlen=sizeof(*a);}else{struct sockaddr_in6*a=(struct sockaddr_in6*)&dst;a->sin6_family=AF_INET6;a->sin6_port=htons(srv->port);InetPtonA(AF_INET6,srv->host,&a->sin6_addr);dlen=sizeof(*a);}u_long nb=1;ioctlsocket(fd,FIONBIO,&nb);connect(fd,(struct sockaddr*)&dst,dlen);fd_set w;FD_ZERO(&w);FD_SET(fd,&w);struct timeval tv={0,300000};select(0,NULL,&w,NULL,&tv);nb=0;ioctlsocket(fd,FIONBIO,&nb);int err=0;int elen=sizeof(err);getsockopt(fd,SOL_SOCKET,SO_ERROR,(char*)&err,&elen);if(err==0){unsigned char hello[1200];size_t n=build_fake_client_hello(hello,sizeof(hello),sni);if(n>0)send_all(fd,hello,n);}closesocket(fd);}
static void send_all_decoys(ServerAddr*srv){if(g_cfg.ttl_count==0){send_one_decoy(srv,5);return;}for(int i=0;i<g_cfg.ttl_count;i++)send_one_decoy(srv,g_cfg.ttl_list[i]);}
typedef struct{ SOCKET from; SOCKET to; } RelayArgs;
static DWORD WINAPI relay_thread(LPVOID a){RelayArgs*ra=(RelayArgs*)a;char buf[16384];int n;while((n=recv(ra->from,buf,sizeof(buf),0))>0){if(send_all(ra->to,buf,n)<n)break;}shutdown(ra->to,SD_SEND);free(ra);return 0;}
static void send_fragmented(SOCKET fd,const unsigned char*data,size_t len){int one=1;setsockopt(fd,IPPROTO_TCP,TCP_NODELAY,(char*)&one,sizeof(one));size_t off=0;while(off<len){size_t chunk=off==0?4:32;size_t n=len-off<chunk?len-off:chunk;send_all(fd,data+off,n);off+=n;Sleep(2);}}
static int connect_with_timeout(SOCKET fd,struct sockaddr*dst,int dlen,int ms){u_long nb=1;ioctlsocket(fd,FIONBIO,&nb);int rc=connect(fd,dst,dlen);if(rc==0){nb=0;ioctlsocket(fd,FIONBIO,&nb);return 0;}if(WSAGetLastError()!=WSAEWOULDBLOCK){nb=0;ioctlsocket(fd,FIONBIO,&nb);return -1;}fd_set w;FD_ZERO(&w);FD_SET(fd,&w);struct timeval tv={ms/1000,(ms%1000)*1000};rc=select(0,NULL,&w,NULL,&tv);nb=0;ioctlsocket(fd,FIONBIO,&nb);if(rc<=0)return -1;int err=0;int elen=sizeof(err);getsockopt(fd,SOL_SOCKET,SO_ERROR,(char*)&err,&elen);return err==0?0:-1;}
static int race_servers(void){for(int i=0;i<g_cfg.server_count;i++){SOCKET fd=socket(g_cfg.servers[i].family,SOCK_STREAM,IPPROTO_TCP);if(fd==INVALID_SOCKET)continue;struct sockaddr_storage dst;int dl=0;memset(&dst,0,sizeof(dst));if(g_cfg.servers[i].family==AF_INET){struct sockaddr_in*a=(struct sockaddr_in*)&dst;a->sin_family=AF_INET;a->sin_port=htons(g_cfg.servers[i].port);InetPtonA(AF_INET,g_cfg.servers[i].host,&a->sin_addr);dl=sizeof(*a);}else{struct sockaddr_in6*a=(struct sockaddr_in6*)&dst;a->sin6_family=AF_INET6;a->sin6_port=htons(g_cfg.servers[i].port);InetPtonA(AF_INET6,g_cfg.servers[i].host,&a->sin6_addr);dl=sizeof(*a);}int ok=(connect_with_timeout(fd,(struct sockaddr*)&dst,dl,800)==0);closesocket(fd);if(ok)return i;}return g_cfg.server_count>0?0:-1;}
static DWORD WINAPI handle_client(LPVOID arg){SOCKET cfd=*(SOCKET*)arg;free(arg);char hbuf[8192];int hl=0;int got=0;DWORD to=5000;setsockopt(cfd,SOL_SOCKET,SO_RCVTIMEO,(char*)&to,sizeof(to));while(got<5){int n=recv(cfd,hbuf+got,5-got,0);if(n<=0){closesocket(cfd);return 0;}got+=n;}if((unsigned char)hbuf[0]!=0x16){closesocket(cfd);return 0;}int rl=((unsigned char)hbuf[3]<<8)|(unsigned char)hbuf[4];int need=5+rl;if(need>(int)sizeof(hbuf))need=sizeof(hbuf);while(got<need){int n=recv(cfd,hbuf+got,need-got,0);if(n<=0)break;got+=n;}to=0;setsockopt(cfd,SOL_SOCKET,SO_RCVTIMEO,(char*)&to,sizeof(to));int win=race_servers();if(win<0){closesocket(cfd);return 0;}ServerAddr srv=g_cfg.servers[win];send_all_decoys(&srv);int jit=g_cfg.jitter_min_ms;int range=g_cfg.jitter_max_ms-g_cfg.jitter_min_ms;if(range>0)jit+=rand()%range;Sleep(jit);SOCKET sfd=socket(srv.family,SOCK_STREAM,IPPROTO_TCP);if(sfd==INVALID_SOCKET){closesocket(cfd);return 0;}struct sockaddr_storage dst;int dl=0;memset(&dst,0,sizeof(dst));if(srv.family==AF_INET){struct sockaddr_in*a=(struct sockaddr_in*)&dst;a->sin_family=AF_INET;a->sin_port=htons(srv.port);InetPtonA(AF_INET,srv.host,&a->sin_addr);dl=sizeof(*a);}else{struct sockaddr_in6*a=(struct sockaddr_in6*)&dst;a->sin6_family=AF_INET6;a->sin6_port=htons(srv.port);InetPtonA(AF_INET6,srv.host,&a->sin6_addr);dl=sizeof(*a);}if(connect(sfd,(struct sockaddr*)&dst,dl)!=0){closesocket(cfd);closesocket(sfd);return 0;}if(g_cfg.fragment_real)send_fragmented(sfd,(unsigned char*)hbuf,got);else send_all(sfd,hbuf,got);RelayArgs*a1=(RelayArgs*)malloc(sizeof(RelayArgs));a1->from=cfd;a1->to=sfd;RelayArgs*a2=(RelayArgs*)malloc(sizeof(RelayArgs));a2->from=sfd;a2->to=cfd;HANDLE t1=CreateThread(NULL,0,relay_thread,a1,0,NULL);HANDLE t2=CreateThread(NULL,0,relay_thread,a2,0,NULL);WaitForSingleObject(t1,INFINITE);WaitForSingleObject(t2,INFINITE);CloseHandle(t1);CloseHandle(t2);closesocket(cfd);closesocket(sfd);return 0;}
int main(int argc,char**argv){srand((unsigned)time(NULL));WSADATA wsa;WSAStartup(MAKEWORD(2,2),&wsa);const char*cfg=argc>1?argv[1]:"cloak.conf";FILE*ch=fopen(cfg,"r");if(!ch){FILE*f=fopen(cfg,"w");if(f){fprintf(f,"listen_port = 40443\nconnect_list = 162.159.198.79:443\nfallback_ports = 443,2053,2083,2087,2096,8443\nsni_list = www.hcaptcha.com,www.speedtest.net,www.bing.com\nttl_list = 4,5,6,8\njitter_min_ms = 20\njitter_max_ms = 80\nfragment = false\nadaptive = true\n");fclose(f);}printf("no config at '%s' -- wrote starter\n",cfg);return 0;}fclose(ch);if(load_config(cfg)<0)return 1;if(g_cfg.fallback_port_count==0)parse_fallback_ports("443,2053,2083,2087,2096,8443");expand_servers();if(g_cfg.server_count==0)return 1;if(g_cfg.sni_count==0)parse_sni_list("www.hcaptcha.com,www.speedtest.net,www.bing.com");if(g_cfg.ttl_count==0)parse_ttl_list("4,5,6,8");SOCKET lfd=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(lfd==INVALID_SOCKET)return 1;int yes=1;setsockopt(lfd,SOL_SOCKET,SO_REUSEADDR,(char*)&yes,sizeof(yes));struct sockaddr_in addr;memset(&addr,0,sizeof(addr));addr.sin_family=AF_INET;addr.sin_addr.s_addr=INADDR_ANY;addr.sin_port=htons(g_cfg.listen_port);if(bind(lfd,(struct sockaddr*)&addr,sizeof(addr))<0)return 1;listen(lfd,64);printf("cloak -- listening on 127.0.0.1:%d\n",g_cfg.listen_port);while(1){struct sockaddr_in ca;int cl=sizeof(ca);SOCKET*cfd=(SOCKET*)malloc(sizeof(SOCKET));*cfd=accept(lfd,(struct sockaddr*)&ca,&cl);if(*cfd==INVALID_SOCKET){free(cfd);continue;}CreateThread(NULL,0,handle_client,cfd,0,NULL);}return 0;}
